[project]
name = "interservice"
version = "0.1.2"
requires-python = ">=3.9"
dependencies = ["boto3", "httpx", "fastapi", "PyJWT"]
description = "Lightweight JWT-based service-to-service auth for Movomint backends"
license = {text = "MIT"}

[tool.setuptools.packages.find]
include = ["interservice"]
